Repository lspcontainers/lspcontainers.nvim, pull requests merged in 2021-05, with the labels that each got.

#2 #1: Initial Implementation
  README.md
  lua/lspcontainers/init.lua
Labels: enhancement

#3 docs(readme): fix typo in lspconfig setup
  README.md
Labels: documentation, good first issue

#4 Add support for lsp root_dir
  README.md
  lua/lspcontainers/init.lua
Labels: enhancement

#5 create table for supported languages and allow enduser to provide more languages
  lua/lspcontainers/init.lua
Labels: enhancement

#6 Initial support for the Go language server (gopls)
  lua/lspcontainers/init.lua
Labels: enhancement

#9 #8: Adds newly implemented LSPs
  README.md
  lua/lspcontainers/init.lua
Labels: documentation, enhancement

#11 #10: Add pyright LSP
  README.md
  lua/lspcontainers/init.lua
Labels: documentation, enhancement

#12 feat(rust): Add rust language server
  README.md
  lua/lspcontainers/init.lua
Labels: enhancement

#19 feat(config): adds pyls, svelte and terraformls
  README.md
  lua/lspcontainers/init.lua
Labels: documentation, enhancement

#20 Test the list of languages matches lspconfig names
  .github/workflows/test.yml
  .gitignore
  lua/lspcontainers/init.lua
  scripts/test.lua
  scripts/test.sh
Labels: enhancement
