Repository lspcontainers/lspcontainers.nvim, pull requests merged in 2021-06, with the labels that each got.

#23 feature: bumping terraforls to 0.18.0
  lua/lspcontainers/init.lua
Labels: enhancement

#24 Adding new ls
  README.md
  lua/lspcontainers/init.lua
Labels: documentation, enhancement

#21 optional overriding of container cmd
  lua/lspcontainers/init.lua
Labels: enhancement, help wanted
